
! DO NOT EDIT THIS FILE!!!  
!  
! This file is automatically generated by write_network.py at 
! compile-time.  
!  
! To modify the species carried by the network, edit the appropriate inputs 
! file.

! An automatically generated "null" network.  This provides the properties
! of a set of non-reacting species.
!
! network_name     -- a descriptive name of the network
!
! nspec            -- the number of species
!
! aion             -- atomic number
! zion             -- proton number
!
! spec_names       -- the name of the isotope
! short_spec_names -- an abbreviated form of the species name
!
!
! This module contains two routines:
!
!  network_init()        -- initialize the isotope properties
!
!  network_species_index -- return the index of the species given its name
!

module actual_network

  use bl_types

  implicit none

  integer, parameter :: nspec = 3
  integer, parameter :: nspec_evolve = 3
  integer, parameter :: naux = 0

  character (len=16), save :: spec_names(nspec) 
  character (len= 5), save :: short_spec_names(nspec)
  character (len= 5), save :: short_aux_names(naux)

  character (len=*), parameter :: network_name = "general-aproxCNOsolar.net"

  real(kind=dp_t), save :: aion(nspec), zion(nspec)

  integer, parameter :: nrates = 0

contains
  
  subroutine actual_network_init()

    implicit none

    spec_names(1) = "hydrogen-1"
    spec_names(2) = "helium-4"
    spec_names(3) = "cno"

    short_spec_names(1) = "H1"
    short_spec_names(2) = "He4"
    short_spec_names(3) = "cno"

    aion(1) = 1.0
    aion(2) = 4.0
    aion(3) = 14.87

    zion(1) = 1.0
    zion(2) = 2.0
    zion(3) = 7.43

  end subroutine actual_network_init

  
  subroutine actual_network_finalize

    implicit none

    ! Nothing to do here.

  end subroutine actual_network_finalize

end module actual_network
