
! DO NOT EDIT THIS FILE!!!  
!  
! This file is automatically generated by write_network.py at 
! compile-time.  
!  
! To modify the species carried by the network, edit the appropriate inputs 
! file.

! An automatically generated "null" network.  This provides the properties
! of a set of non-reacting species.
!
! network_name     -- a descriptive name of the network
!
! nspec            -- the number of species
!
! aion             -- atomic number
! zion             -- proton number
!
! spec_names       -- the name of the isotope
! short_spec_names -- an abbreviated form of the species name
!
!
! This module contains two routines:
!
!  network_init()        -- initialize the isotope properties
!
!  network_species_index -- return the index of the species given its name
!

module network

  use bl_types

  implicit none

  integer, parameter :: nspec = 15
  integer, parameter :: naux = 0

  character (len=16), save :: spec_names(nspec) 
  character (len= 5), save :: short_spec_names(nspec)
  character (len= 5), save :: short_aux_names(naux)

  character (len=*), parameter :: network_name = "general-H_core.net"

  real(kind=dp_t), save :: aion(nspec), zion(nspec)

  logical, save :: network_initialized = .false.

contains
  
  subroutine network_init()

    spec_names(1) = "hydrogen-1"
    spec_names(2) = "helium-3"
    spec_names(3) = "helium-4"
    spec_names(4) = "carbon-12"
    spec_names(5) = "nitrogen-14"
    spec_names(6) = "oxygen-16"
    spec_names(7) = "neon-20"
    spec_names(8) = "magnesium-24"
    spec_names(9) = "silicon-28"
    spec_names(10) = "sulfur-32"
    spec_names(11) = "argon-36"
    spec_names(12) = "calcium-40"
    spec_names(13) = "titanium-44"
    spec_names(14) = "chromium-48"
    spec_names(15) = "iron-54"

    short_spec_names(1) = "H1"
    short_spec_names(2) = "He3"
    short_spec_names(3) = "He4"
    short_spec_names(4) = "C12"
    short_spec_names(5) = "N14"
    short_spec_names(6) = "O16"
    short_spec_names(7) = "Ne20"
    short_spec_names(8) = "Mg24"
    short_spec_names(9) = "Si28"
    short_spec_names(10) = "S32"
    short_spec_names(11) = "Ar36"
    short_spec_names(12) = "Ca40"
    short_spec_names(13) = "Ti44"
    short_spec_names(14) = "Cr48"
    short_spec_names(15) = "Fe54"

    aion(1) = 1.0
    aion(2) = 3.0
    aion(3) = 4.0
    aion(4) = 12.0
    aion(5) = 14.0
    aion(6) = 16.0
    aion(7) = 20.0
    aion(8) = 24.0
    aion(9) = 28.0
    aion(10) = 32.0
    aion(11) = 36.0
    aion(12) = 40.0
    aion(13) = 44.0
    aion(14) = 48.0
    aion(15) = 54.0

    zion(1) = 1.0
    zion(2) = 2.0
    zion(3) = 2.0
    zion(4) = 6.0
    zion(5) = 7.0
    zion(6) = 8.0
    zion(7) = 10.0
    zion(8) = 12.0
    zion(9) = 14.0
    zion(10) = 16.0
    zion(11) = 18.0
    zion(12) = 20.0
    zion(13) = 22.0
    zion(14) = 24.0
    zion(15) = 26.0

    network_initialized = .true.

  end subroutine network_init

  
  function network_species_index(name)

    character(len=*) :: name
    integer :: network_species_index, n

    network_species_index = -1

    do n = 1, nspec
       if (name == spec_names(n)) then
          network_species_index = n
          exit
       endif
    enddo
    
    return
  end function network_species_index


  subroutine network_finalize()

  end subroutine network_finalize

end module network
