NDEBUG :=
MPI    := t
OMP    := 

COMP   := gfortran

MKVERBOSE := t

MAESTRO_TOP_DIR := ../..

EOS_TOP_DIR      := $(MAESTRO_TOP_DIR)/TEST_PROBLEMS/polytrope_test2
EOS_DIR          := idealgas

CONDUCTIVITY_DIR := constant
NETWORK_DIR := null

EXTRA_DIR := Util/random \
             TEST_PROBLEMS/polytrope_test2

include $(MAESTRO_TOP_DIR)/GMaestro.mak
