! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module probin_module

  use bl_types
  use bl_space
  use bl_constants_module
  use pred_parameters
  use bc_module

  implicit none

  private

  real (kind=dp_t), save, public :: pert_factor = 0.1d0
  real (kind=dp_t), save, public :: dens_base = 1.65d-3
  real (kind=dp_t), save, public :: pres_base = 1.65d6
  real (kind=dp_t), save, public :: y_pert_center = 0.7d0
  real (kind=dp_t), save, public :: pert_width = 0.025d0
  logical, save, public :: do_isentropic = .true.
  integer, save, public :: verbose = 0
  logical, save, public :: do_alltoallv = .false.
  logical, save, public :: the_knapsack_verbosity = .false.
  character (len=256), save, public :: job_name = ""
  logical, save, public :: barrier_timers = .false.
  character (len=256), save, public :: model_file = "model.hse"
  logical, save, public :: perturb_model = .false.
  real (kind=dp_t), save, public :: stop_time = -1.d0
  integer, save, public :: max_step = 1
  real (kind=dp_t), save, public :: cflfac = 0.5d0
  real (kind=dp_t), save, public :: init_shrink = 1.d0
  real (kind=dp_t), save, public :: small_dt = 1.d-10
  real (kind=dp_t), save, public :: max_dt_growth = 1.1d0
  real (kind=dp_t), save, public :: max_dt = 1.0d33
  real (kind=dp_t), save, public :: fixed_dt = -1.0d0
  real (kind=dp_t), save, public :: nuclear_dt_fac = -1.0d0
  logical, save, public :: use_soundspeed_firstdt = .false.
  logical, save, public :: use_divu_firstdt = .false.
  real (kind=dp_t), save, public :: prob_lo_x = ZERO
  real (kind=dp_t), save, public :: prob_lo_y = ZERO
  real (kind=dp_t), save, public :: prob_lo_z = ZERO
  real (kind=dp_t), save, public :: prob_hi_x = 1.d0
  real (kind=dp_t), save, public :: prob_hi_y = 1.d0
  real (kind=dp_t), save, public :: prob_hi_z = 1.d0
  character (len=256), save, public :: test_set = ''
  integer, save, public :: bcx_lo = SLIP_WALL
  integer, save, public :: bcx_hi = SLIP_WALL
  integer, save, public :: bcy_lo = SLIP_WALL
  integer, save, public :: bcy_hi = SLIP_WALL
  integer, save, public :: bcz_lo = SLIP_WALL
  integer, save, public :: bcz_hi = SLIP_WALL
  character (len=256), save, public :: xlo_boundary_type = ""
  character (len=256), save, public :: xhi_boundary_type = ""
  character (len=256), save, public :: ylo_boundary_type = ""
  character (len=256), save, public :: yhi_boundary_type = ""
  character (len=256), save, public :: zlo_boundary_type = ""
  character (len=256), save, public :: zhi_boundary_type = ""
  integer, save, public :: spherical_in = 0
  logical, save, public :: octant = .false.
  integer, save, public :: do_2d_planar_octant = 0
  integer, save, public :: dm_in = 2
  integer, save, public :: max_levs = 1
  integer, save, public :: max_grid_size = 64
  integer, save, public :: max_grid_size_1 = -1
  integer, save, public :: max_grid_size_2 = -1
  integer, save, public :: max_grid_size_3 = -1
  logical, save, public :: change_max_grid_size_1 = .false.
  integer, save, public :: regrid_int = -1
  integer, save, public :: amr_buf_width = -1
  integer, save, public :: ref_ratio = 2
  integer, save, public :: n_cellx = -1
  integer, save, public :: n_celly = -1
  integer, save, public :: n_cellz = -1
  integer, save, public :: drdxfac = 1
  integer, save, public :: the_sfc_threshold = 5
  integer, save, public :: the_layout_verbosity = 0
  integer, save, public :: the_copy_cache_max = 25
  integer, save, public :: minwidth = 8
  integer, save, public :: blocking_factor = 8
  real (kind=dp_t), save, public :: min_eff = 0.9d0
  logical, save, public :: dump_grid_file = .false.
  integer, save, public :: plot_int = 0
  real (kind=dp_t), save, public :: plot_deltat = -1.d0
  integer, save, public :: chk_int = 0
  logical, save, public :: plot_h_with_use_tfromp = .true.
  logical, save, public :: plot_spec = .true.
  logical, save, public :: plot_omegadot = .true.
  logical, save, public :: plot_Hext = .false.
  logical, save, public :: plot_Hnuc = .true.
  logical, save, public :: plot_eta = .false.
  logical, save, public :: plot_trac = .false.
  logical, save, public :: plot_base = .false.
  logical, save, public :: plot_gpi = .true.
  logical, save, public :: plot_cs = .false.
  character (len=256), save, public :: plot_base_name = "plt"
  character (len=256), save, public :: check_base_name = "chk"
  integer, save, public :: nOutFiles = 64
  logical, save, public :: lUsingNFiles = .true.
  logical, save, public :: single_prec_plotfiles = .false.
  integer, save, public :: diag_buf_size = 10
  logical, save, public :: plot_ad_excess = .false.
  logical, save, public :: plot_processors = .false.
  logical, save, public :: plot_pidivu = .false.
  integer, save, public :: init_iter = 4
  integer, save, public :: init_divu_iter = 4
  integer, save, public :: restart = -1
  logical, save, public :: restart_into_finer = .false.
  logical, save, public :: do_initial_projection = .true.
  integer, save, public :: mg_verbose = 0
  integer, save, public :: cg_verbose = 0
  integer, save, public :: hg_bottom_solver = -1
  integer, save, public :: mg_bottom_solver = -1
  integer, save, public :: max_mg_bottom_nlevels = 1000
  integer, save, public :: mg_bottom_nu = 10
  logical, save, public :: hg_dense_stencil = .true.
  logical, save, public :: use_hypre = .false.
  logical, save, public :: do_sponge = .false.
  real (kind=dp_t), save, public :: sponge_kappa = 10.d0
  real (kind=dp_t), save, public :: sponge_center_density = 3.d6
  real (kind=dp_t), save, public :: sponge_start_factor = 3.333d0
  logical, save, public :: plot_sponge_fdamp = .false.
  real (kind=dp_t), save, public :: anelastic_cutoff = 3.d6
  real (kind=dp_t), save, public :: base_cutoff_density = 3.d6
  real (kind=dp_t), save, public :: buoyancy_cutoff_factor = 5.0
  real (kind=dp_t), save, public :: dpdt_factor = 0.d0
  logical, save, public :: do_planar_invsq_grav = .false.
  real (kind=dp_t), save, public :: planar_invsq_mass = 0.d0
  logical, save, public :: evolve_base_state = .true.
  logical, save, public :: fix_base_state = .false.
  logical, save, public :: do_smallscale = .false.
  logical, save, public :: do_eos_h_above_cutoff = .true.
  integer, save, public :: enthalpy_pred_type = predict_rhohprime
  integer, save, public :: species_pred_type = 1
  logical, save, public :: use_delta_gamma1_term = .false.
  logical, save, public :: use_etarho = .true.
  integer, save, public :: slope_order = 4
  real (kind=dp_t), save, public :: grav_const = -1.5d10
  logical, save, public :: use_tfromp = .false.
  integer, save, public :: ppm_type = 1
  integer, save, public :: bds_type = 0
  integer, save, public :: beta_type = 1
  logical, save, public :: use_linear_grav_in_beta = .false.
  real (kind=dp_t), save, public :: rotational_frequency = ZERO
  real (kind=dp_t), save, public :: co_latitude = ZERO
  real (kind=dp_t), save, public :: rotation_radius = 1.0d6
  real (kind=dp_t), save, public :: mach_max_abort = -1.d0
  logical, save, public :: drive_initial_convection = .false.
  logical, save, public :: restart_with_vel_field = .false.
  logical, save, public :: use_alt_energy_fix = .false.
  logical, save, public :: use_thermal_diffusion = .false.
  integer, save, public :: temp_diffusion_formulation = 2
  integer, save, public :: thermal_diffusion_type = 1
  real (kind=dp_t), save, public :: conductivity_constant = 1.0d0
  logical, save, public :: do_burning = .true.
  character (len=256), save, public :: burner_threshold_species = ""
  real (kind=dp_t), save, public :: burner_threshold_cutoff = 1.d-10
  real (kind=dp_t), save, public :: small_temp = 5.d6
  real (kind=dp_t), save, public :: small_dens = 1.d-5
  logical, save, public :: use_eos_e_instead_of_h = .false.
  integer, save, public :: s0_interp_type = 3
  integer, save, public :: w0_interp_type = 2
  integer, save, public :: s0mac_interp_type = 1
  integer, save, public :: w0mac_interp_type = 1
  logical, save, public :: use_particles = .false.
  logical, save, public :: store_particle_vels = .false.
  logical, save, public :: do_heating = .false.
  integer, save, public :: sdc_iters = 1
  logical, save, public :: sdc_couple_mac_velocity = .false.
  logical, save, public :: sdc_hold_mac_velocity = .false.

  real(dp_t), save, public    :: burning_cutoff_density  ! note: presently not runtime parameter


  ! Keep track of the inputs file that was used to read in runtime
  ! parameters.  This filename will be written into the job_info file.
  character (len=128), save, public :: inputs_file_used = ""


  ! These will be allocated and defined below
  logical,    allocatable, save, public :: nodal(:)
  logical,    allocatable, save, public :: pmask(:)
  real(dp_t), allocatable, save, public :: prob_lo(:)
  real(dp_t), allocatable, save, public :: prob_hi(:)

end module probin_module


module extern_probin_module

  use bl_types
  use bl_space

  implicit none

  private



end module extern_probin_module


module runtime_init_module

  use bl_types
  use probin_module
  use extern_probin_module

  implicit none

  namelist /probin/ pert_factor
  namelist /probin/ dens_base
  namelist /probin/ pres_base
  namelist /probin/ y_pert_center
  namelist /probin/ pert_width
  namelist /probin/ do_isentropic
  namelist /probin/ verbose
  namelist /probin/ do_alltoallv
  namelist /probin/ the_knapsack_verbosity
  namelist /probin/ job_name
  namelist /probin/ barrier_timers
  namelist /probin/ model_file
  namelist /probin/ perturb_model
  namelist /probin/ stop_time
  namelist /probin/ max_step
  namelist /probin/ cflfac
  namelist /probin/ init_shrink
  namelist /probin/ small_dt
  namelist /probin/ max_dt_growth
  namelist /probin/ max_dt
  namelist /probin/ fixed_dt
  namelist /probin/ nuclear_dt_fac
  namelist /probin/ use_soundspeed_firstdt
  namelist /probin/ use_divu_firstdt
  namelist /probin/ prob_lo_x
  namelist /probin/ prob_lo_y
  namelist /probin/ prob_lo_z
  namelist /probin/ prob_hi_x
  namelist /probin/ prob_hi_y
  namelist /probin/ prob_hi_z
  namelist /probin/ test_set
  namelist /probin/ bcx_lo
  namelist /probin/ bcx_hi
  namelist /probin/ bcy_lo
  namelist /probin/ bcy_hi
  namelist /probin/ bcz_lo
  namelist /probin/ bcz_hi
  namelist /probin/ xlo_boundary_type
  namelist /probin/ xhi_boundary_type
  namelist /probin/ ylo_boundary_type
  namelist /probin/ yhi_boundary_type
  namelist /probin/ zlo_boundary_type
  namelist /probin/ zhi_boundary_type
  namelist /probin/ spherical_in
  namelist /probin/ octant
  namelist /probin/ do_2d_planar_octant
  namelist /probin/ dm_in
  namelist /probin/ max_levs
  namelist /probin/ max_grid_size
  namelist /probin/ max_grid_size_1
  namelist /probin/ max_grid_size_2
  namelist /probin/ max_grid_size_3
  namelist /probin/ change_max_grid_size_1
  namelist /probin/ regrid_int
  namelist /probin/ amr_buf_width
  namelist /probin/ ref_ratio
  namelist /probin/ n_cellx
  namelist /probin/ n_celly
  namelist /probin/ n_cellz
  namelist /probin/ drdxfac
  namelist /probin/ the_sfc_threshold
  namelist /probin/ the_layout_verbosity
  namelist /probin/ the_copy_cache_max
  namelist /probin/ minwidth
  namelist /probin/ blocking_factor
  namelist /probin/ min_eff
  namelist /probin/ dump_grid_file
  namelist /probin/ plot_int
  namelist /probin/ plot_deltat
  namelist /probin/ chk_int
  namelist /probin/ plot_h_with_use_tfromp
  namelist /probin/ plot_spec
  namelist /probin/ plot_omegadot
  namelist /probin/ plot_Hext
  namelist /probin/ plot_Hnuc
  namelist /probin/ plot_eta
  namelist /probin/ plot_trac
  namelist /probin/ plot_base
  namelist /probin/ plot_gpi
  namelist /probin/ plot_cs
  namelist /probin/ plot_base_name
  namelist /probin/ check_base_name
  namelist /probin/ nOutFiles
  namelist /probin/ lUsingNFiles
  namelist /probin/ single_prec_plotfiles
  namelist /probin/ diag_buf_size
  namelist /probin/ plot_ad_excess
  namelist /probin/ plot_processors
  namelist /probin/ plot_pidivu
  namelist /probin/ init_iter
  namelist /probin/ init_divu_iter
  namelist /probin/ restart
  namelist /probin/ restart_into_finer
  namelist /probin/ do_initial_projection
  namelist /probin/ mg_verbose
  namelist /probin/ cg_verbose
  namelist /probin/ hg_bottom_solver
  namelist /probin/ mg_bottom_solver
  namelist /probin/ max_mg_bottom_nlevels
  namelist /probin/ mg_bottom_nu
  namelist /probin/ hg_dense_stencil
  namelist /probin/ use_hypre
  namelist /probin/ do_sponge
  namelist /probin/ sponge_kappa
  namelist /probin/ sponge_center_density
  namelist /probin/ sponge_start_factor
  namelist /probin/ plot_sponge_fdamp
  namelist /probin/ anelastic_cutoff
  namelist /probin/ base_cutoff_density
  namelist /probin/ buoyancy_cutoff_factor
  namelist /probin/ dpdt_factor
  namelist /probin/ do_planar_invsq_grav
  namelist /probin/ planar_invsq_mass
  namelist /probin/ evolve_base_state
  namelist /probin/ fix_base_state
  namelist /probin/ do_smallscale
  namelist /probin/ do_eos_h_above_cutoff
  namelist /probin/ enthalpy_pred_type
  namelist /probin/ species_pred_type
  namelist /probin/ use_delta_gamma1_term
  namelist /probin/ use_etarho
  namelist /probin/ slope_order
  namelist /probin/ grav_const
  namelist /probin/ use_tfromp
  namelist /probin/ ppm_type
  namelist /probin/ bds_type
  namelist /probin/ beta_type
  namelist /probin/ use_linear_grav_in_beta
  namelist /probin/ rotational_frequency
  namelist /probin/ co_latitude
  namelist /probin/ rotation_radius
  namelist /probin/ mach_max_abort
  namelist /probin/ drive_initial_convection
  namelist /probin/ restart_with_vel_field
  namelist /probin/ use_alt_energy_fix
  namelist /probin/ use_thermal_diffusion
  namelist /probin/ temp_diffusion_formulation
  namelist /probin/ thermal_diffusion_type
  namelist /probin/ conductivity_constant
  namelist /probin/ do_burning
  namelist /probin/ burner_threshold_species
  namelist /probin/ burner_threshold_cutoff
  namelist /probin/ small_temp
  namelist /probin/ small_dens
  namelist /probin/ use_eos_e_instead_of_h
  namelist /probin/ s0_interp_type
  namelist /probin/ w0_interp_type
  namelist /probin/ s0mac_interp_type
  namelist /probin/ w0mac_interp_type
  namelist /probin/ use_particles
  namelist /probin/ store_particle_vels
  namelist /probin/ do_heating
  namelist /probin/ sdc_iters
  namelist /probin/ sdc_couple_mac_velocity
  namelist /probin/ sdc_hold_mac_velocity

  private

  public :: probin

  public :: runtime_init, runtime_close

contains

  subroutine runtime_init()

    use f2kcli
    use parallel
    use bl_IO_module
    use bl_prof_module
    use bl_error_module
    use bl_constants_module
    use knapsack_module
    use multifab_module, only: multifab_set_alltoallv
    use cluster_module
    use layout_module
    use pred_parameters
    use bc_module
    
    integer    :: narg, farg

    character(len=128) :: fname
    character(len=128) :: probin_env

    logical    :: lexist, need_inputs
    integer    :: natonce, myproc, nprocs, nsets, myset, iset, ibuff(1)
    integer    :: wakeuppid, waitforpid, tag, un, ierr
    real(dp_t) :: pistart, piend, pitotal, pistartall, piendall, pitotalall
    real(dp_t) :: pitotal_max, pitotalall_max

    type(bl_prof_timer), save :: bpt

    call build(bpt, "runtime_init")

    narg = command_argument_count()

    need_inputs = .true.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! initialize the runtime parameters
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    !
    ! Don't have more than 64 processes trying to read from disk at once.
    !
    natonce = min(64,parallel_nprocs())
    myproc  = parallel_myproc()
    nprocs  = parallel_nprocs()
    nsets   = ((nprocs + (natonce - 1)) / natonce)
    myset   = (myproc / natonce)
    pistart = 0.d0
    piend   = 0.d0

    pistartall = parallel_wtime()

    ! loop over the processor groups (sets) and read the inputs file.
    ! We look first for an environment variable "PROBIN", then at the
    ! first argument to the executable, and finally for a file named
    ! inputs_maestro
    do iset = 0, nsets-1

       if (myset .eq. iset) then

          pistart = parallel_wtime()
          
          call get_environment_variable('PROBIN', probin_env, status = ierr)
          if ( need_inputs .AND. ierr == 0 ) then
             un = unit_new()
             open(unit=un, file = probin_env, status = 'old', action = 'read')
             read(unit=un, nml = probin)
             close(unit=un)
             inputs_file_used = probin_env
             need_inputs = .false.
          end if

          farg = 1
          if ( need_inputs .AND. narg >= 1 ) then
             call get_command_argument(farg, value = fname)
             inquire(file = fname, exist = lexist )
             if ( lexist ) then
                farg = farg + 1
                un = unit_new()
                open(unit=un, file = fname, status = 'old', action = 'read')
                read(unit=un, nml = probin)
                close(unit=un)
                inputs_file_used = fname
                need_inputs = .false.
             end if
          end if

          inquire(file = 'inputs_maestro', exist = lexist)
          if ( need_inputs .AND. lexist ) then
             un = unit_new()
             open(unit=un, file = 'inputs_maestro', status = 'old', action = 'read')
             read(unit=un, nml = probin)
             close(unit=un)
             inputs_file_used = 'inputs_maestro'
             need_inputs = .false.
          end if

          piend = parallel_wtime()

          ibuff(1)  = 0
          wakeuppid = myproc + natonce
          tag       = mod(myproc,natonce)
          
          if (wakeuppid < nprocs) call parallel_send(ibuff, wakeuppid, tag)

       end if

      if (myset .eq. (iset + 1)) then

         tag        = mod(myproc,natonce)
         waitforpid = myproc - natonce

         call parallel_recv(ibuff, waitforpid, tag)
      endif

    end do

    piendall   = parallel_wtime()
    pitotal    = piend - pistart
    pitotalall = piendall - pistartall

    call parallel_reduce(pitotal_max,    pitotal,    MPI_MAX, &
                         proc = parallel_IOProcessorNode())
    call parallel_reduce(pitotalall_max, pitotalall, MPI_MAX, &
                         proc = parallel_IOProcessorNode())

    if (parallel_IOProcessor()) then
      print*, "PROBINIT max time   = ", pitotal_max
      print*, "PROBINIT total time = ", pitotalall_max
    endif

    do while ( farg <= narg )
       call get_command_argument(farg, value = fname)
       select case (fname)


       case ('--pert_factor')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) pert_factor

       case ('--dens_base')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) dens_base

       case ('--pres_base')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) pres_base

       case ('--y_pert_center')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) y_pert_center

       case ('--pert_width')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) pert_width

       case ('--do_isentropic')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_isentropic

       case ('--verbose')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) verbose

       case ('--do_alltoallv')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_alltoallv

       case ('--the_knapsack_verbosity')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) the_knapsack_verbosity

       case ('--job_name')
          farg = farg + 1
          call get_command_argument(farg, value = job_name)

       case ('--barrier_timers')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) barrier_timers

       case ('--model_file')
          farg = farg + 1
          call get_command_argument(farg, value = model_file)

       case ('--perturb_model')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) perturb_model

       case ('--stop_time')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) stop_time

       case ('--max_step')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_step

       case ('--cflfac')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) cflfac

       case ('--init_shrink')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) init_shrink

       case ('--small_dt')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) small_dt

       case ('--max_dt_growth')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_dt_growth

       case ('--max_dt')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_dt

       case ('--fixed_dt')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) fixed_dt

       case ('--nuclear_dt_fac')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) nuclear_dt_fac

       case ('--use_soundspeed_firstdt')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_soundspeed_firstdt

       case ('--use_divu_firstdt')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_divu_firstdt

       case ('--prob_lo_x')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_lo_x

       case ('--prob_lo_y')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_lo_y

       case ('--prob_lo_z')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_lo_z

       case ('--prob_hi_x')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_hi_x

       case ('--prob_hi_y')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_hi_y

       case ('--prob_hi_z')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) prob_hi_z

       case ('--test_set')
          farg = farg + 1
          call get_command_argument(farg, value = test_set)

       case ('--bcx_lo')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcx_lo

       case ('--bcx_hi')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcx_hi

       case ('--bcy_lo')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcy_lo

       case ('--bcy_hi')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcy_hi

       case ('--bcz_lo')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcz_lo

       case ('--bcz_hi')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bcz_hi

       case ('--xlo_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = xlo_boundary_type)

       case ('--xhi_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = xhi_boundary_type)

       case ('--ylo_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = ylo_boundary_type)

       case ('--yhi_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = yhi_boundary_type)

       case ('--zlo_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = zlo_boundary_type)

       case ('--zhi_boundary_type')
          farg = farg + 1
          call get_command_argument(farg, value = zhi_boundary_type)

       case ('--spherical_in')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) spherical_in

       case ('--octant')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) octant

       case ('--do_2d_planar_octant')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_2d_planar_octant

       case ('--dm_in')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) dm_in

       case ('--max_levs')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_levs

       case ('--max_grid_size')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_grid_size

       case ('--max_grid_size_1')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_grid_size_1

       case ('--max_grid_size_2')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_grid_size_2

       case ('--max_grid_size_3')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_grid_size_3

       case ('--change_max_grid_size_1')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) change_max_grid_size_1

       case ('--regrid_int')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) regrid_int

       case ('--amr_buf_width')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) amr_buf_width

       case ('--ref_ratio')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) ref_ratio

       case ('--n_cellx')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) n_cellx

       case ('--n_celly')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) n_celly

       case ('--n_cellz')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) n_cellz

       case ('--drdxfac')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) drdxfac

       case ('--the_sfc_threshold')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) the_sfc_threshold

       case ('--the_layout_verbosity')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) the_layout_verbosity

       case ('--the_copy_cache_max')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) the_copy_cache_max

       case ('--minwidth')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) minwidth

       case ('--blocking_factor')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) blocking_factor

       case ('--min_eff')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) min_eff

       case ('--dump_grid_file')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) dump_grid_file

       case ('--plot_int')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_int

       case ('--plot_deltat')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_deltat

       case ('--chk_int')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) chk_int

       case ('--plot_h_with_use_tfromp')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_h_with_use_tfromp

       case ('--plot_spec')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_spec

       case ('--plot_omegadot')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_omegadot

       case ('--plot_Hext')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_Hext

       case ('--plot_Hnuc')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_Hnuc

       case ('--plot_eta')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_eta

       case ('--plot_trac')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_trac

       case ('--plot_base')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_base

       case ('--plot_gpi')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_gpi

       case ('--plot_cs')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_cs

       case ('--plot_base_name')
          farg = farg + 1
          call get_command_argument(farg, value = plot_base_name)

       case ('--check_base_name')
          farg = farg + 1
          call get_command_argument(farg, value = check_base_name)

       case ('--nOutFiles')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) nOutFiles

       case ('--lUsingNFiles')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) lUsingNFiles

       case ('--single_prec_plotfiles')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) single_prec_plotfiles

       case ('--diag_buf_size')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) diag_buf_size

       case ('--plot_ad_excess')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_ad_excess

       case ('--plot_processors')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_processors

       case ('--plot_pidivu')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_pidivu

       case ('--init_iter')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) init_iter

       case ('--init_divu_iter')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) init_divu_iter

       case ('--restart')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) restart

       case ('--restart_into_finer')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) restart_into_finer

       case ('--do_initial_projection')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_initial_projection

       case ('--mg_verbose')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) mg_verbose

       case ('--cg_verbose')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) cg_verbose

       case ('--hg_bottom_solver')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) hg_bottom_solver

       case ('--mg_bottom_solver')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) mg_bottom_solver

       case ('--max_mg_bottom_nlevels')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) max_mg_bottom_nlevels

       case ('--mg_bottom_nu')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) mg_bottom_nu

       case ('--hg_dense_stencil')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) hg_dense_stencil

       case ('--use_hypre')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_hypre

       case ('--do_sponge')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_sponge

       case ('--sponge_kappa')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sponge_kappa

       case ('--sponge_center_density')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sponge_center_density

       case ('--sponge_start_factor')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sponge_start_factor

       case ('--plot_sponge_fdamp')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) plot_sponge_fdamp

       case ('--anelastic_cutoff')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) anelastic_cutoff

       case ('--base_cutoff_density')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) base_cutoff_density

       case ('--buoyancy_cutoff_factor')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) buoyancy_cutoff_factor

       case ('--dpdt_factor')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) dpdt_factor

       case ('--do_planar_invsq_grav')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_planar_invsq_grav

       case ('--planar_invsq_mass')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) planar_invsq_mass

       case ('--evolve_base_state')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) evolve_base_state

       case ('--fix_base_state')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) fix_base_state

       case ('--do_smallscale')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_smallscale

       case ('--do_eos_h_above_cutoff')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_eos_h_above_cutoff

       case ('--enthalpy_pred_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) enthalpy_pred_type

       case ('--species_pred_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) species_pred_type

       case ('--use_delta_gamma1_term')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_delta_gamma1_term

       case ('--use_etarho')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_etarho

       case ('--slope_order')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) slope_order

       case ('--grav_const')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) grav_const

       case ('--use_tfromp')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_tfromp

       case ('--ppm_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) ppm_type

       case ('--bds_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) bds_type

       case ('--beta_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) beta_type

       case ('--use_linear_grav_in_beta')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_linear_grav_in_beta

       case ('--rotational_frequency')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) rotational_frequency

       case ('--co_latitude')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) co_latitude

       case ('--rotation_radius')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) rotation_radius

       case ('--mach_max_abort')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) mach_max_abort

       case ('--drive_initial_convection')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) drive_initial_convection

       case ('--restart_with_vel_field')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) restart_with_vel_field

       case ('--use_alt_energy_fix')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_alt_energy_fix

       case ('--use_thermal_diffusion')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_thermal_diffusion

       case ('--temp_diffusion_formulation')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) temp_diffusion_formulation

       case ('--thermal_diffusion_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) thermal_diffusion_type

       case ('--conductivity_constant')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) conductivity_constant

       case ('--do_burning')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_burning

       case ('--burner_threshold_species')
          farg = farg + 1
          call get_command_argument(farg, value = burner_threshold_species)

       case ('--burner_threshold_cutoff')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) burner_threshold_cutoff

       case ('--small_temp')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) small_temp

       case ('--small_dens')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) small_dens

       case ('--use_eos_e_instead_of_h')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_eos_e_instead_of_h

       case ('--s0_interp_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) s0_interp_type

       case ('--w0_interp_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) w0_interp_type

       case ('--s0mac_interp_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) s0mac_interp_type

       case ('--w0mac_interp_type')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) w0mac_interp_type

       case ('--use_particles')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) use_particles

       case ('--store_particle_vels')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) store_particle_vels

       case ('--do_heating')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) do_heating

       case ('--sdc_iters')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sdc_iters

       case ('--sdc_couple_mac_velocity')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sdc_couple_mac_velocity

       case ('--sdc_hold_mac_velocity')
          farg = farg + 1
          call get_command_argument(farg, value = fname)
          read(fname, *) sdc_hold_mac_velocity



       case ('--')
          farg = farg + 1
          exit

       case default
          if ( .not. parallel_q() ) then
             write(*,*) 'UNKNOWN option = ', fname
             call bl_error("MAIN")
          end if
       end select

       farg = farg + 1
    end do


    !-------------------------------------------------------------------------
    ! some sanity checks and set some defaults
    !-------------------------------------------------------------------------

    if (ref_ratio .ne. 2) then
       call bl_error("Only supporting ref_ratio = 2")
    end if

    if (plot_spec .eqv. .false.) plot_omegadot = .false.

    if (use_tfromp .and. dpdt_factor /= 0.0d0) then
       call bl_error("ERROR: use_tfromp = T requires dpdt_factor = 0 to decouple enthalpy")
    endif

    if (max_grid_size_1 .eq. -1) then
       max_grid_size_1 = max_grid_size
    end if

    if (max_grid_size_2 .eq. -1) then
       max_grid_size_2 = max_grid_size
    end if

    if (max_grid_size_3 .eq. -1) then
       max_grid_size_3 = max_grid_size
    end if

    if (spherical_in == 1 .and. do_planar_invsq_grav) then
       call bl_error("ERROR: do_planar_invsq_grav invalid for spherical geometries")
    endif

    if (do_2d_planar_octant == 1) then
       if ( dm_in /= 2) then	
       	  call bl_error("ERROR: do_2d_planar_octant requires dm_in = 2")
       endif
       if (spherical_in ==1) then
       	  call bl_error("ERROR: do_2d_planar_octant requires spherical_in = 0")
       endif
       if (prob_lo_y /= ZERO) then
       	  call bl_error("ERROR: do_2d_planar_octant requires prob_lo(2) = 0")
       endif
    endif

    if (do_planar_invsq_grav) then
       if ( (dm_in == 2 .and. prob_lo_y <= ZERO) .or. &
            (dm_in == 3 .and. prob_lo_z <= ZERO) )then
          call bl_error("ERROR: do_planar_invsq_grav requires prob_lo(dm) > 0")
       endif
    endif

    if (max_mg_bottom_nlevels .lt. 2) then
       call bl_error("ERROR: max_mg_bottom_nlevels must be greater than 1")
    endif

    ! make sure that the buffer width for tagging is atleast as big as
    ! the regrid interval
    if (regrid_int > 0 .and. amr_buf_width < regrid_int) then
       if (parallel_IOProcessor()) then
          print *,"************************************************************************"
          print *,"WARNING: regrid_int > 0 but amr_buf_width < regrid_int"
          print *,"         setting amr_buf_width = regrid_int"
          print *,"************************************************************************"          
       endif
       amr_buf_width = regrid_int
    endif

    if ( max_levs > 1 .AND. test_set .eq. '' .AND. regrid_int < 0 ) then
        call bl_error("ERROR: must set regrid_int to use AMR")
    end	 if

    if (ppm_type .lt. 0 .or. ppm_type .gt. 2) then
       call bl_error("invalid ppm_type")
    end if

    if (bds_type .lt. 0 .or. bds_type .gt. 1) then
       call bl_error("invalid bds_type")
    end if

    if (do_smallscale) then
       if (parallel_IOProcessor()) then
          print *,"************************************************************************"
          print *,"WARNING: do_smallscale=T; Make sure your initialization sets p0=constant"
          print *,"************************************************************************"
       end if
       if (evolve_base_state) then
          call bl_error("do_smallscale requires evolve_base_state = F")
       end if
       if (beta_type .ne. 3) then
          call bl_error("do_smallscale requires beta_type = 3")
       end if
    end if

    ! check species and enthalpy types
    if (.not. (species_pred_type == predict_rhoprime_and_X .or. &
               species_pred_type == predict_rhoX .or. &
               species_pred_type == predict_rho_and_X)) then
       call bl_error("invalid species_pred_type")
    endif

    if (.not. (enthalpy_pred_type == predict_rhoh .or. &
               enthalpy_pred_type == predict_rhohprime .or. &
               enthalpy_pred_type == predict_h .or. &
               enthalpy_pred_type == predict_T_then_rhohprime .or. &
               enthalpy_pred_type == predict_T_then_h .or. &
               enthalpy_pred_type == predict_hprime .or. &
               enthalpy_pred_type == predict_Tprime_then_h)) then
       call bl_error("invalid enthalpy_pred_type")
    endif


    ! use_tfromp = T is not compatible with enthalpy_pred_types
    ! predict_T_then_rhohprime or predict_T_then_h, since the
    ! temperature update in react state doesn't 'see' the energy
    ! release.
    if (use_tfromp .and. &
         (enthalpy_pred_type == predict_T_then_rhohprime .or. &
          enthalpy_pred_type == predict_T_then_h)) then
       call bl_error("use_tfromp not supported with enthalpy_pred_type predict_T_then_rhohprime or predict_T_then_h")
    endif


    ! for the moment, set the cutoff for burning to be base_cutoff_density
    burning_cutoff_density = base_cutoff_density

    ! initialize nodal
    allocate(nodal(dm_in))
    nodal = .true.

    ! if the string versions of the boundary conditions were set, then	
    ! these override the integer values
    if (.not. xlo_boundary_type == "") &
         bcx_lo = bc_string_to_integer(trim(xlo_boundary_type))

    if (.not. xhi_boundary_type == "") &
         bcx_hi = bc_string_to_integer(trim(xhi_boundary_type))

    if (.not. ylo_boundary_type == "") &
         bcy_lo = bc_string_to_integer(trim(ylo_boundary_type))

    if (.not. yhi_boundary_type == "") &
         bcy_hi = bc_string_to_integer(trim(yhi_boundary_type))

    if (.not. zlo_boundary_type == "") &
         bcz_lo = bc_string_to_integer(trim(zlo_boundary_type))

    if (.not. zhi_boundary_type == "") &
         bcz_hi = bc_string_to_integer(trim(zhi_boundary_type))
    
    if (bcx_lo == UNDEFINED) call bl_error("xlo_boundary_type invalid")
    if (bcx_hi == UNDEFINED) call bl_error("xhi_boundary_type invalid")
    if (bcy_lo == UNDEFINED) call bl_error("ylo_boundary_type invalid")
    if (bcy_hi == UNDEFINED) call bl_error("yhi_boundary_type invalid")
    if (bcz_lo == UNDEFINED) call bl_error("zlo_boundary_type invalid")
    if (bcz_hi == UNDEFINED) call bl_error("zhi_boundary_type invalid")


    ! initialize pmask
    allocate(pmask(dm_in))
    pmask = .FALSE.
    if (bcx_lo .eq. -1 .and. bcx_hi .eq. -1) pmask(1) = .true.
    if (dm_in > 1) then
       if (bcy_lo .eq. -1 .and. bcy_hi .eq. -1) pmask(2) = .true.
    end if
    if (dm_in > 2) then
       if (bcz_lo .eq. -1 .and. bcz_hi .eq. -1) pmask(3) = .true.
    end if

    ! initialize prob_lo and prob_hi
    allocate(prob_lo(dm_in))
    prob_lo(1) = prob_lo_x
    if (dm_in > 1) prob_lo(2) = prob_lo_y
    if (dm_in > 2) prob_lo(3) = prob_lo_z
    allocate(prob_hi(dm_in))
    prob_hi(1) = prob_hi_x
    if (dm_in > 1) prob_hi(2) = prob_hi_y
    if (dm_in > 2) prob_hi(3) = prob_hi_z


    call cluster_set_minwidth(minwidth)
    call cluster_set_blocking_factor(blocking_factor)
    call cluster_set_min_eff(min_eff)

    if (do_alltoallv) call multifab_set_alltoallv(.true.)
    
    call knapsack_set_verbose(the_knapsack_verbosity)

    call layout_set_verbosity(the_layout_verbosity)
    call layout_set_copyassoc_max(the_copy_cache_max)
    call layout_set_sfc_threshold(the_sfc_threshold)

    call destroy(bpt)
    
  end subroutine runtime_init

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  subroutine runtime_close()

    use probin_module

    deallocate(nodal)
    deallocate(pmask)
    deallocate(prob_lo)
    deallocate(prob_hi)

  end subroutine runtime_close

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

end module runtime_init_module
