NDEBUG := t
MPI    := t
OMP    :=

COMP := Intel


MKVERBOSE := t

# define the location of the fParallel root directory
FPARALLEL := ../..


# include the main Makefile stuff
include $(FPARALLEL)/mk/GMakedefs.mak


# define the packages to build this problem
Fmdirs := MAESTRO/wdconvect \
          boxlib \
          mg \
          MAESTRO \
          extern/helmeos \
          extern/conducteos \
          extern/constants \
          extern/networks/ignition \
          extern/VODE

Fmpack := $(foreach dir, $(Fmdirs), $(FPARALLEL)/$(dir)/GPackage.mak)
Fmlocs := $(foreach dir, $(Fmdirs), $(FPARALLEL)/$(dir))

include $(Fmpack)
VPATH_LOCATIONS += $(Fmlocs)
FINCLUDE_LOCATIONS += $(Fmlocs)


# define the build instructions for the executable
main.$(suf).exe: $(objects)
	$(LINK.f90) -o main.$(suf).exe $(objects) $(libraries)
	@echo SUCCESS

# define the runtime parameter files
PROBIN_PARAMETERS := ../_parameters ./_parameters.wdconvect
PROBIN_TEMPLATE   := ../probin.template

probin.f90: $(PROBIN_PARAMETERS) $(PROBIN_TEMPLATE)
	../write_probin.py -t $(PROBIN_TEMPLATE) $(PROBIN_PARAMETERS)



# include the Makefile rules
include $(FPARALLEL)/mk/GMakerules.mak

