#!/usr/bin/env python
"""
Plot an angle-averaged plotfile using matplotlib.

Donald E. Willcox
"""

from __future__ import print_function
import AngleAveragedProfile
import numpy as np
import matplotlib.pyplot as plt
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('infile', type=str,
                    help='Name of angle-averaged profile to plot.')
parser.add_argument('-f', '--format', type=str, default='png',
                    help='Format of the desired output files. Can be, e.g. "png" or "eps". Defaults to "png".')
parser.add_argument('-rup', '--radius_upper', type=float,
                    help='Upper bound for the plotted radius.')
args = parser.parse_args()


if __name__ == '__main__':
    # Read the file into an angle-averaged profile object
    aaprof = AngleAveragedProfile(args.infile)
    # Plot the variables in the file
    aaprof.plot_all_vars(args.format, args.radius_upper)
