#!/usr/bin/env python
"""
Plot an angle-averaged plotfile using matplotlib.

Donald E. Willcox
"""

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('infile', type=str,
                    help='Name of angle-averaged profile to plot.')
parser.add_argument('-f', '--format', type=str, default='png',
                    help='Format of the desired output files. Can be, e.g. "png" or "eps". Defaults to "png".')
parser.add_argument('-rup', '--radius_upper', type=float,
                    help='Upper bound for the plotted radius.')
args = parser.parse_args()

# Angle-averaged profile Class
class AngleAveragedProfile(object):
    def __init__(self, filename=None):
        self.init_vars()
        if filename:
            self.read_from_file(filename)
            
    def init_vars(self):
        self.header = {}
        self.data = {}
        self.data_keys = []
        self.filename = ''
        
    def read_from_file(self, filename):
        # Clear my variables
        self.init_vars()
        self.filename = filename
        # Given a profile filename, read the profile
        f = open(filename, 'r')
        # Get the header global values
        num_sep = 0 # Number of '-----' separator lines encountered
        readColumnLabels = False # True if next line has column labels
        for line in f:
            ls = line.strip()
            if ls[0] == '#' or readColumnLabels:
                if readColumnLabels:
                    cl = []
                    if ls[0] == '#':
                        ls = ls[1:]
                    for ci in ls.split('  '):
                        ci = ci.strip()
                        # Need to check because splitting by '  '
                        # can yield ' ' which strip to ''.
                        if ci:
                            # If field is enclosed in [ ] brackets, remove them
                            if ci[0] == '[' and ci[-1] == ']':
                                ci = ci[1:-1].strip()
                            cl.append(ci) 
                    self.data_keys = cl
                    print(self.data_keys)
                    for ci in cl:
                        self.data[ci] = []
                    readColumnLabels = False
                    num_sep = 0
                else:
                    # See if there's an equals sign and get value
                    if '=' in ls:
                        k, v = ls[2:].split('=', 1)
                        k = k.strip()
                        v = [float(vf) for vf in v.strip().split()]
                        if len(v) > 1:
                            v = np.array(v)
                        else:
                            v = v[0]
                        self.header[k] = v
                    elif '----------------------------' in ls:
                        num_sep += 1
                        if num_sep == 3 and not readColumnLabels:
                            readColumnLabels = True
            else:
                # Read data line
                ld = [float(di) for di in ls.split()]
                for k, v in zip(self.data_keys, ld):
                    self.data[k].append(v)
        f.close()
        # Turn data into numpy arrays
        for k in self.data.keys():
            self.data[k] = np.array(self.data[k])

    def plot_var(self, var, fmt='png', rup=None):
        # Plot the variable corresponding to the data key var
        # Independent axis is radius r
        # Plots are log scale on the dependent axis
        if var not in self.data.keys():
            return
        fig = plt.figure()
        ax = fig.add_subplot(111)
        idxup = -1
        if rup:
            ax.set_xlim([0, rup])
            # Get the lowest index where radius > rup
            idxup = np.where(self.data['r'] > rup)[0][0]
        # PLOT LOG SCALE
        ax.plot(self.data['r'][:idxup], np.log10(self.data[var][:idxup]), color='green')
        ax.set_xlabel('r')
        ax.set_ylabel('$\mathrm{Log_{10} \ ' + var + '}$')
        lwb = max(-10.0, np.floor(np.log10(np.amin(self.data[var][:idxup]))))
        upb = np.ceil(np.log10(np.amax(self.data[var][:idxup])))
        if upb - lwb < 1.0:
            upb = lwb + 1.0
        ax.set_ylim((lwb, upb))
        # List the time above the plot
        tart = ax.text(0.0, 1.01, 'time = {}'.format(self.header['time']),
                       transform=ax.transAxes,
                       verticalalignment='bottom')
        outname = '.'.join([self.filename, var.replace(' ','-'), fmt])
        plt.tight_layout()
        if fmt=='png':
            plt.savefig(outname, bbox_extra_artists=(tart,), dpi=300)
        else:
            plt.savefig(outname, bbox_extra_artists=(tart,))
        plt.close(fig)
            
    def plot_all_vars(self, fmt='png', rup=None):
        # Plot all variables in the profile and save
        # fmt is the suffix passed to savefig
        for var in self.data.keys():
            if var != 'r':
                self.plot_var(var, fmt, rup)

if __name__ == '__main__':
    # Read the file into an angle-averaged profile object
    aaprof = AngleAveragedProfile(args.infile)
    # Plot the variables in the file
    aaprof.plot_all_vars(args.format, args.radius_upper)
    
