#!/bin/ksh
#PBS -A ast106
#PBS -N test_react
#PBS -j oe
#PBS -q batch
#PBS -l walltime=04:00:00,nodes=2

# this script runs with 16 threads, 1 MPI tasks/node, and 2 nodes on titan 
#

export PSC_OMP_AFFINITY=FALSE
export OMP_NUM_THREADS=16

cd $PBS_O_WORKDIR

# -n  is the total number of MPI tasks
# -S  is the number of MPI tasks per NUMA node 
# -N  is the number of MPI tasks per node
# -d  is the number of OpenMP threads per MPI task (must match OMP_NUM_THREADS)
# -ss forces MPI tasks to only allocate memory in their local NUMA node.
#   This can boost performance by preventing costly remote memory I/O, though 
#   it also restricts the amount of memory available to MPI tasks.

aprun -n 2 -N 1 -d $OMP_NUM_THREADS -ss ./main.Linux.Cray.mpi.omp.exe inputs_ignition

