NDEBUG :=
MPI    := t
OMP    := 

COMP   := gfortran

MKVERBOSE := t

FPARALLEL := ../../..

Fmdirs := MAESTRO/TEST_PROBLEMS/polytrope_test

EOS_DIR := MAESTRO/TEST_PROBLEMS/polytrope_test/idealgas
CONDUCTIVITY_DIR := extern/conductivity/constant
NETWORK_DIR := extern/networks/null

EXTRA_DIR := extern/random

include $(FPARALLEL)/MAESTRO/GMaestro.mak
