NDEBUG := t
MPI    := t
OMP    := 

COMP   := gfortran

MKVERBOSE := t

MAESTRO_TOP_DIR := ../..

Fmdirs := 

EOS_TOP_DIR := $(MAESTRO_TOP_DIR)/TEST_PROBLEMS/stand_prob
EOS_DIR := idealgas

CONDUCTIVITY_DIR := constant
NETWORK_DIR := null

EXTRA_DIR := Util/random \
             TEST_PROBLEMS/stand_prob

include $(MAESTRO_TOP_DIR)/GMaestro.mak
