NDEBUG := t
MPI    := t
OMP    := 

COMP   := gfortran

MKVERBOSE := t

FPARALLEL := ../../..

EOS_DIR := MAESTRO/TEST_PROBLEMS/stand_prob/idealgas
CONDUCTIVITY_DIR := extern/conductivity/constant
NETWORK_DIR := extern/networks/null

EXTRA_DIR := extern/random

include $(FPARALLEL)/MAESTRO/GMaestro.mak
